### ISSUE TITLE
monolinker.exe crashes when System.ServiceMode.Primitives is referenced in any used projects

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#126]
System.ServiceMode.Primitives crashes monolinker.exe.

Our whole WebAsm build process is broken because it is used and referenced by protobuf-net.

**TODO:**
- [x] Try to build protobuf-net without it (remove depending classes during this)
    - [x] Fix the now introduced exception when running `fusee.exe protoscheme` 
    - [x] Export all *.fus-files used within the examples again
- [x] Fix protobuf-net's newly introduced feature: `AsReference is obsolete` (@griestopf)
See #133 

After that, merge #164.

**Comment by wrestledBearOnce** [comment]
I managed to build a protobuf version without primitives and without that nasty exception when running `fusee.exe` with the `protoscheme` verb. 
Needs some more refactoring, cleaning and documentation and is going to be a fork within our group after that.

I furthermore built a new `monolinker.exe` with verbose and exception logging. I'm going to integrate and replace the "old" exe within the webassembly.sdk build task nuget package. The next time our linker process fails we can at least enable debug messages.
